### ISSUE TITLE
Image部件的一个bug?

### ISSUE THREAD

**Issue by qq332769043** [01org/intel-iot-services-orchestration-layer#46]
Image部件的url不能显示本地图片：“file:///xxxx/xxx.jpg”  但是可以正常显示http://xxx/xx.jpg图片   注：我是在windows下测试的。

**Comment by jiangzidong** [comment]
请问你本地图片的路径是怎么样的? 有实际例子和截图吗?

**Comment by jonathanding** [comment]
Due to security concerns, Chrome cannot access local file by default. You could change this setting by starting Chrome with "--allow-file-access-from-files" option supplied. 

You may google search "Chrome local file security" for more details, e.g.  http://stackoverflow.com/questions/29371600/chrome-browser-security-implications-of-allow-file-access-from-files

**Comment by qq332769043** [comment]
Thank you very much
